on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Amazon-test:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository (this is needed to work within the repo context)
      - name: Checkout code
        uses: actions/checkout@v3

      # Install AWS CLI (optional if it's already installed in the image)
      - name: Install AWS CLI
        run: sudo apt-get update && sudo apt-get install -y awscli

      # Install Python 3.12
      - name: Install Python 3.12
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y ppa:deadsnakes/ppa
          sudo apt-get update
          sudo apt-get install -y python3.12 python3.12-venv python3.12-distutils

      # Upgrade pip and setuptools
      - name: Upgrade pip and setuptools
        run: |
          python3.12 -m ensurepip --upgrade
          python3.12 -m pip install --upgrade pip setuptools wheel

      # Verify Python 3.12 installation
      - name: Verify Python 3.12 installation
        run: python3.12 --version

      # Configure AWS credentials (using GitHub Secrets)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      # Build the SAM application
      - name: Build SAM Application
        run: |
          cd sam_lambda/toru010-ImageGenerator
          sam build

      # Deploy the SAM application
      - name: Deploy SAM Application
        run: |
          cd sam_lambda/toru010-ImageGenerator
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset