on:
  push:
    branches:
      - main       # Trigger on pushes to main
      - '**'       # Trigger on pushes to any branch
  workflow_dispatch:  # Allow manual workflow runs

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
              
      # Install Terraform
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Plan or Apply based on branch
      - name: Terraform Plan or Apply
        env:
          TF_VAR_bucket_name: "pgr301-couch-explorers"
        run: |
          echo "Checking branch: ${{ github.ref }}"
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "Running terraform apply..."
            terraform plan -out=tfplan
            terraform apply -auto-approve tfplan
          else
            echo "Running terraform plan..."
            terraform plan

              
